# Generated by Django 5.0.6 on 2024-05-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя автора', max_length=100, verbose_name='Имя автора')),
                ('last_name', models.CharField(help_text='Введите фамилию автора', max_length=100, verbose_name='Фамилия автора')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения')),
                ('about', models.TextField(help_text='Введите сведения об авторе', verbose_name='Сведения об авторе')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите жанр', max_length=200, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите язык', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_App', models.CharField(help_text='Введите название приложения', max_length=200, verbose_name='Название приложения')),
                ('date_of_out', models.CharField(help_text='Введите год выхода', max_length=4, verbose_name='Год выхода')),
                ('summary', models.TextField(help_text='Введите краткое содержание приложения', max_length=1000, verbose_name='Описание приложения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=7, verbose_name='Цена (руб.)')),
                ('photo', models.ImageField(help_text='Введите изображение приложения', upload_to='images', verbose_name='Изображение')),
                ('author', models.ManyToManyField(help_text='Выберите создателей ', null=True, to='CLR_APP.author', verbose_name='Создатели приложения')),
                ('genre', models.ForeignKey(help_text='Выберите жанр для приложения', null=True, on_delete=django.db.models.deletion.CASCADE, to='CLR_APP.genre', verbose_name='Жанр')),
                ('language', models.ForeignKey(help_text='Выберите язык', null=True, on_delete=django.db.models.deletion.CASCADE, to='CLR_APP.language', verbose_name='Язык')),
            ],
        ),
    ]
